services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/intel-nuc-homeassistant:2022.12.8
    #ports: # ports ignored when network mode is host
    #  - 8123:8123 # port for web interface and rest api
    volumes:
      - ./config/ha:/config
      - ./camera-snapshots:/camera-snapshots
      - /var/run/dbus/:/var/run/dbus/:z # required after Airthings Custom Component changed to bleak bluetooth lib
    environment:
      - TZ=Europe/Oslo
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    depends_on:
      - zwavejs2mqtt

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:8.6.2
    #ports: # ports ignored when network mode is host
    #  - '8091:8091' # port for web interface
    #  - '4000:4000' # port for zwave-js websocket server used by HA, default set to 3000, but changed in web interface to 4000 since Grafana runs at 3000
    volumes:
      - ./data/zwavejs2mqtt:/usr/src/app/store
    environment:
      - TZ=Europe/Oslo
    restart: unless-stopped
    network_mode: "host"
    devices:
      - "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_82946f4e7794eb11b5353a703d98b6d1-if00-port0:/dev/ttyACM0"
    tty: true
    stop_signal: SIGINT
