version: '3.8'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/intel-nuc-homeassistant:2021.12.6
    #ports: # ports ignored when network mode is host
    #  - 8123:8123 # port for web interface and rest api
    volumes:
      - ./config/ha:/config
      - ./camera-snapshots:/camera-snapshots
    environment:
      - TZ=Europe/Oslo
    restart: unless-stopped
    network_mode: "host"
    depends_on:
      - zwavejs2mqtt

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:6.2.0
    #ports: # ports ignored when network mode is host
    #  - '8091:8091' # port for web interface
    #  - '4000:4000' # port for zwave-js websocket server used by HA, default set to 3000, but changed in web interface to 4000 since Grafana runs at 3000
    volumes:
      - ./data/zwavejs2mqtt:/usr/src/app/store
    environment:
      - TZ=Europe/Oslo
    restart: unless-stopped
    network_mode: "host"
    devices:
      - "/dev/serial/by-id/usb-0658_0200-if00:/dev/ttyACM0"
    tty: true
    stop_signal: SIGINT
