blueprint:
  name: Light off when no motion
  description: Turn off lights when motion is cleared
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
    light_target: # since it is not possible to define multiple domains for selector, we define two inputs
      name: Light
      description: optional
      default: {}
      selector:
        target:
          entity:
            domain: light
    switch_target: # since it is not possible to define multiple domains for selector, we define two inputs
      name: Light Switch
      description: optional
      default: {}
      selector:
        target:
          entity:
            domain: switch
    no_motion_wait:
      name: Turn off wait time
      description: Time to leave the light on after last motion is detected
      default: 5
      selector:
        number:
          min: 0
          max: 30
          step: 1
          unit_of_measurement: "minutes"
          mode: slider

mode: single

variables:
  light_target: !input light_target
  switch_target: !input switch_target

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "on"
  to: "off"
  for:
    minutes: !input no_motion_wait

action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ light_target != {} and switch_target == {} }}'
        sequence:
          - service: homeassistant.turn_off
            target: !input light_target
      - conditions:
          - condition: template
            value_template: '{{ light_target == {} and switch_target != {} }}'
        sequence:
          - service: homeassistant.turn_off
            target: !input switch_target
      - conditions:
          - condition: template
            value_template: '{{ light_target != {} and switch_target != {} }}'
        sequence:
          - service: homeassistant.turn_off
            target: !input light_target
          - service: homeassistant.turn_off
            target: !input switch_target
