- cal_id: smarthytte@slomic.no
  entities:
  - device_id: smarthytte_slomic_no
    ignore_availability: true
    name: smarthytte@slomic.no
    track: false

- cal_id: e_2_no#weeknum@group.v.calendar.google.com
  entities:
  - device_id: week_numbers
    ignore_availability: true
    name: Week Numbers
    track: false

- cal_id: no.norwegian#holiday@group.v.calendar.google.com
  entities:
  - device_id: helligdager_i_norge
    ignore_availability: true
    name: Helligdager i Norge
    track: false

- cal_id: c_2k8jn65m107ct36bfj2ud9pfn0@group.calendar.google.com
  entities:
    - device_id: booking
      ignore_availability: true
      name: Booking
      track: true

- cal_id: addressbook#contacts@group.v.calendar.google.com
  entities:
  - device_id: contacts
    ignore_availability: true
    name: Contacts
    track: false
