# Must be defined as general group and not light group because mix of "light" and "switch" domains
bad_1_lights:
  name: Bad 1 lights
  icon: mdi:lightbulb-multiple
  entities:
    - light.fibaro_dimmer_bad_1_level
    - switch.fibaro_switch_bad_1_switch

# Must be defined as general group and not light group because mix of "light" and "switch" domains
bad_2_lights:
  name: Bad 2 lights
  icon: mdi:lightbulb-multiple
  entities:
    - light.fibaro_dimmer_bad_2_level
    - switch.fibaro_switch_bad_2_switch
