  api_version: 2
  ssl: false
  host: localhost
  port: 8086
  token: !secret influxdb_token
  organization: !secret influxdb_organization
  bucket: home_assistant
  max_retries: 3
  tags:
    source: home-assistant
  include:
    entities:
      # Bad 1
      - sensor.aeotec_multisensor_bad_1_temperature
      - climate.heatit_thermostat_bad_1_mode
      - sensor.aeotec_multisensor_bad_1_battery_level
      - sensor.aeotec_multisensor_bad_1_luminance
      - sensor.aeotec_multisensor_bad_1_relative_humidity
      # Bad 2
      - sensor.aeotec_multisensor_bad_2_temperature
      - climate.heatit_thermostat_bad_2_mode
      - sensor.aeotec_multisensor_bad_2_battery_level
      - sensor.aeotec_multisensor_bad_2_luminance
      - sensor.aeotec_multisensor_bad_2_relative_humidity
      # Bod 1
      - sensor.fibaro_door_sensor_bod_1_temperature
      - sensor.fibaro_wall_plug_bod_1_energy
      - sensor.fibaro_wall_plug_bod_1_power
      - switch.fibaro_wall_plug_bod_1_switch
      - sensor.fibaro_door_sensor_bod_1_battery_level
      - sensor.id_lock_bod_1_battery_level
      # Gang 1
      - climate.heatit_thermostat_gang_1_mode
      - sensor.sensative_window_sensor_gang_1_battery_level
      - sensor.fibaro_multisensor_gang_1_temperature
      - sensor.fibaro_multisensor_gang_1_battery_level
      - sensor.fibaro_multisensor_gang_1_luminance
      - sensor.fibaro_multisensor_gang_1_seismic_intensity
      - sensor.aarlo_battery_level_hovedinngang
      # Gang 2
      - sensor.fibaro_multisensor_gang_2_temperature
      - sensor.fibaro_multisensor_gang_2_battery_level
      - sensor.fibaro_multisensor_gang_2_luminance
      - sensor.fibaro_multisensor_gang_2_seismic_intensity
      - sensor.sensative_window_sensor_gang_2_battery_level
      # Soverom 1
      - sensor.sensative_window_sensor_soverom_1_battery_level
      - sensor.fibaro_multisensor_soverom_1_temperature
      - sensor.fibaro_multisensor_soverom_1_battery_level
      - sensor.fibaro_multisensor_soverom_1_luminance
      - sensor.fibaro_multisensor_soverom_1_seismic_intensity
      - sensor.sensative_window_sensor_soverom_1_battery_level
      # Soverom 2
      - sensor.fibaro_multisensor_soverom_2_temperature
      - sensor.fibaro_wall_plug_soverom_2_energy
      - sensor.fibaro_wall_plug_soverom_2_power
      - switch.fibaro_wall_plug_soverom_2_switch
      - sensor.fibaro_multisensor_soverom_2_battery_level
      - sensor.fibaro_multisensor_soverom_2_luminance
      - sensor.fibaro_multisensor_soverom_2_seismic_intensity
      - sensor.sensative_window_sensor_soverom_2_battery_level
      # Soverom 3
      - sensor.fibaro_multisensor_soverom_3_temperature
      - sensor.fibaro_wall_plug_soverom_3_energy
      - sensor.fibaro_wall_plug_soverom_3_power
      - switch.fibaro_wall_plug_soverom_3_switch
      - sensor.fibaro_multisensor_soverom_3_battery_level
      - sensor.fibaro_multisensor_soverom_3_luminance
      - sensor.fibaro_multisensor_soverom_3_seismic_intensity
      - sensor.sensative_window_sensor_soverom_3_battery_level
      # Kjøkken
      - sensor.fibaro_multisensor_kjokken_1_temperature
      - sensor.fibaro_multisensor_kjokken_1_battery_level
      - sensor.fibaro_multisensor_kjokken_1_luminance
      - sensor.fibaro_multisensor_kjokken_1_seismic_intensity
      - sensor.sensative_window_sensor_stue_1_battery_level
      - sensor.aarlo_battery_level_stue_1
      # Stue 1
      - sensor.fibaro_multisensor_stue_1_temperature
      - sensor.fibaro_multisensor_stue_1_battery_level
      - sensor.fibaro_multisensor_stue_1_luminance
      - sensor.fibaro_multisensor_stue_1_seismic_intensity
      - sensor.namron_button_switch_stue_1_battery_level
      - sensor.philips_hue_stue_1_dimmer_switch_battery_level
      # Stue 2
      - sensor.fibaro_multisensor_stue_2_temperature
      - sensor.fibaro_multisensor_stue_2_battery_level
      - sensor.fibaro_multisensor_stue_2_luminance
      - sensor.fibaro_multisensor_stue_2_seismic_intensity
      - sensor.namron_button_switch_stue_2_battery_level
      - sensor.airthings_wave_plus_stue_2_rel_atm_pressure
      - sensor.airthings_wave_plus_stue_2_co2
      - sensor.airthings_wave_plus_stue_2_humidity
      - sensor.airthings_wave_plus_stue_2_radon_1day_avg
      - sensor.airthings_wave_plus_stue_2_radon_longterm_avg
      - sensor.airthings_wave_plus_stue_2_temperature
      - sensor.airthings_wave_plus_stue_2_voc
      - sensor.airthings_wave_plus_stue_2_battery_level
      - sensor.airthings_wave_plus_stue_2_luminance
      # Balkong
      - sensor.aarlo_battery_level_balkong
      - sensor.aarlo_battery_level_balkong_2
      # Hovedinngang
      - sensor.id_lock_hovedinngang_battery_level
      # Weather - Met.no integration
      - weather.met_balkong_hourly
      # Zweather - Værstasjon
      - sensor.zweather_balkong_temperature
      - sensor.zweather_balkong_velocity
      - sensor.zweather_balkong_battery_level
      - sensor.zweather_balkong_humidity
      - sensor.zweather_balkong_barometric_pressure
      - sensor.zweather_balkong_luminance
      # Slomic Jaguar
      - sensor.slomic_jag_odometer
      - sensor.slomic_jag_tyres_front_left_pressure
      - sensor.slomic_jag_tyres_front_right_pressure
      - sensor.slomic_jag_tyres_rear_left_pressure
      - sensor.slomic_jag_tyres_rear_right_pressure
      # Parkering
      - sensor.philips_hue_motion_sensor_parkering_temperature
      - sensor.philips_hue_motion_sensor_parkering_battery_level
      - sensor.philips_hue_motion_sensor_parkering_luminance
      # Booking
      - input_boolean.checked_in
