# HACS Arlo integration
- platform: aarlo
  monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength

# Enables Date & Time as sensor, useful for automation
- platform: time_date
  display_options:
    - 'time'
    - 'date'

# Airthing Wave Plus HACS integration
# Auto discovery (when mac field is empty) does not work, you must first find
# mac address Airthings Wave device by using Bluetooth Scanner mob app for Android
# See https://community.home-assistant.io/t/air-quality-monitor-radon-meter-airthings-wave-plus/102836/13
- platform: airthings_wave
  mac: !secret airthings_wave_mac
  scan_interval: 600 # in seconds (10 minutes)

# Sensor for history statistics of wind speed
- platform: statistics
  name: Wind speed last 5 measurements balkong
  entity_id: sensor.zweather_balkong_velocity_kmh
  sampling_size: 5
  state_characteristic: mean

- platform: command_line
  name: SmartMirror Rpi Temperature - Gang 1
  command: !secret smartmirror_rpi_temperature
  unit_of_measurement: "°C"
  value_template: "{{ value }}"
  scan_interval: 60 # 1 min
